/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

//import com.lowagie.text.document;
import com.itextpdf.testutils.ITextTest;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import myPackage.Homepage;


/**
 *
 * @author Prasenjeet Tambe
 */
public class FullHistoryOfPatient extends javax.swing.JFrame
{

    /**
     * Creates new form FullHistoryOfPatient
     */
    public FullHistoryOfPatient()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblDisplay.setBackground(new java.awt.Color(255, 204, 204));
        tblDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Patient ID", "Name", "Contact", "Age", "Gender", "Blood Group", "Address", "Past disease", "Symptoms", "Diagnosis", "medicines", "Ward Req", "Type"
            }
        ));
        tblDisplay.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblDisplay.setShowGrid(true);
        jScrollPane1.setViewportView(tblDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 13, 750, 420));

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 454, 100, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf_icon.png"))); // NOI18N
        jButton1.setText("Generate PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 452, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        var a = JOptionPane.showConfirmDialog(this, "Do you want to exit?","Select",JOptionPane.OK_CANCEL_OPTION);
        
        if(a == 0)
        {
            this.dispose();
            Homepage.btnFullHistory.setEnabled(true);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown

        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_database","root","mySQL");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from patient inner join patient_report where patient.patientID=patient_report.patientID");
            DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
            tblDisplay.setAutoResizeMode(tblDisplay.AUTO_RESIZE_OFF);
            
            while(rs.next())
            {
                String id = rs.getString("patientID");
                String name = rs.getString("name");
                String contact = rs.getString("contactNumber");
                int age = rs.getInt("age");
                String gender = rs.getString("gender");
                String bg = rs.getString("bloodGroup");
                String address = rs.getString("address");
                String pastDisease = rs.getString("anyMajorDisease");
                String symptom = rs.getString("symptom");
                String diagnosis = rs.getString("diagnosis");
                String medicines = rs.getString("medicines");
                String wardReq = rs.getString("wardReq");
                String wardType = rs.getString("typeOfWard");
                
                Object content[] = {id,name,contact,age,gender,bg,address,pastDisease,symptom,diagnosis,medicines,wardReq,wardType};
                model.addRow(content);
            }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Connection Error");
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path="";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        
        if(x == JFileChooser.APPROVE_OPTION)
        {
            path = j.getSelectedFile().getPath();
        }
        
        Document doc;
        doc = new Document();
        
        try
        {
            PdfWriter.getInstance((com.itextpdf.text.Document) doc, new FileOutputStream(path + "document.pdf"));
            doc.open();
            
            PdfPTable tbl = new PdfPTable(7);
            float[] columnWidths = new float[]{40,200,140,50,100,80,150};
            tbl.setWidths(columnWidths);
//            BaseFont bf = BaseFont.createFont(BaseFont.TIMES_ROMAN, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
//            
//            iTextSharp.text.Font font = new iTextSharp.text.Font(bf, 10, iTextSharp.text.Font.NORMAL);
//
//
//            Paragraph p1 = new Paragraph(new Chunk("Sample text", font));
//            Base
//            tbl.setTotalWidth(200);
//            tbl.setHorizontalAlignment(0);
            tbl.addCell("ID");
            tbl.addCell("Name");
            tbl.addCell("Contact");
            tbl.addCell("Age");
            tbl.addCell("Gender");
            tbl.addCell("BG");
            tbl.addCell("Diagnosis");
            
            for(int i=0 ; i<tblDisplay.getRowCount() ; i++)
            {
                String patientID = tblDisplay.getValueAt(i, 0).toString();
                String name = tblDisplay.getValueAt(i, 1).toString();
                String contact = tblDisplay.getValueAt(i, 2).toString();
                String age = tblDisplay.getValueAt(i, 3).toString();
                String gender = tblDisplay.getValueAt(i, 4).toString();
                String bg = tblDisplay.getValueAt(i, 5).toString();
                String diagnosis = tblDisplay.getValueAt(i, 9).toString();
                
                
                tbl.addCell(patientID);
                tbl.addCell(name);
                tbl.addCell(contact);
                tbl.addCell(age);
                tbl.addCell(gender);
                tbl.addCell(bg);
                tbl.addCell(diagnosis);
            }
            doc.add(tbl);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error"+e);
        }
        
        doc.close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FullHistoryOfPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FullHistoryOfPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FullHistoryOfPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FullHistoryOfPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FullHistoryOfPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplay;
    // End of variables declaration//GEN-END:variables
}
