/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Prasenjeet Tambe
 */
public class Homepage extends javax.swing.JFrame
{

    /**
     * Creates new form homepage
     */
    public Homepage()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnAddNewPatientRecord = new javax.swing.JButton();
        btnAddDiagnosisInformation = new javax.swing.JButton();
        btnFullHistory = new javax.swing.JButton();
        btnUpdatePatientRecord = new javax.swing.JButton();
        btnHospitalInformation = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblHomepageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddNewPatientRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddNewPatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient.png"))); // NOI18N
        btnAddNewPatientRecord.setText("Add New Patient Record");
        btnAddNewPatientRecord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddNewPatientRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddNewPatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewPatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 238, 64));

        btnAddDiagnosisInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddDiagnosisInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add diag.png"))); // NOI18N
        btnAddDiagnosisInformation.setText("Add Disagnosis Information");
        btnAddDiagnosisInformation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddDiagnosisInformation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddDiagnosisInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDiagnosisInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 238, -1));

        btnFullHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFullHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_history1.png"))); // NOI18N
        btnFullHistory.setText("Full History of Patient");
        btnFullHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFullHistory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFullHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnFullHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 238, -1));

        btnUpdatePatientRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdatePatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_update_details.png"))); // NOI18N
        btnUpdatePatientRecord.setText("Update Patient Record");
        btnUpdatePatientRecord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdatePatientRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdatePatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 238, -1));

        btnHospitalInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHospitalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_hospital_information.png"))); // NOI18N
        btnHospitalInformation.setText("Hospital Information");
        btnHospitalInformation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHospitalInformation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHospitalInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospitalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 238, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 238, -1));

        lblHomepageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage_background_1.jpg"))); // NOI18N
        lblHomepageBackground.setText("jLabel1");
        getContentPane().add(lblHomepageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFullHistoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFullHistoryActionPerformed
    {//GEN-HEADEREND:event_btnFullHistoryActionPerformed
        // TODO add your handling code here:
        FullHistoryOfPatient obj;
        obj = new FullHistoryOfPatient();
        obj.setLocationRelativeTo(this);
        obj.setLocation(450, 180);
        obj.setVisible(true);
        
        btnFullHistory.setEnabled(false);
        
    }//GEN-LAST:event_btnFullHistoryActionPerformed

    private void btnUpdatePatientRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdatePatientRecordActionPerformed
    {//GEN-HEADEREND:event_btnUpdatePatientRecordActionPerformed
        // TODO add your handling code here:
        
        UpdatePatientRecord obj = new UpdatePatientRecord();
        obj.setLocationRelativeTo(this);
        obj.setLocation(450, 180);
        obj.setVisible(true);
        
        btnUpdatePatientRecord.setEnabled(false);
    }//GEN-LAST:event_btnUpdatePatientRecordActionPerformed

    private void btnHospitalInformationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHospitalInformationActionPerformed
    {//GEN-HEADEREND:event_btnHospitalInformationActionPerformed
        // TODO add your handling code here:
        HospitalInformation obj = new HospitalInformation();
        obj.setLocationRelativeTo(this);
        obj.setLocation(450, 180);
        obj.setVisible(true);
        
        btnHospitalInformation.setEnabled(false);
    }//GEN-LAST:event_btnHospitalInformationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLogoutActionPerformed
    {//GEN-HEADEREND:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout", "Select", JOptionPane.YES_NO_OPTION);
        
        if(a == 0)
        {
            Login obj;
            obj = new Login();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddNewPatientRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddNewPatientRecordActionPerformed
    {//GEN-HEADEREND:event_btnAddNewPatientRecordActionPerformed
        // TODO add your handling code here:
        AddNewPatientRecord obj =  new AddNewPatientRecord();
        obj.setLocationRelativeTo(this);
        obj.setLocation(450, 180);
        obj.setVisible(true);
        
        btnAddNewPatientRecord.setEnabled(false);
    }//GEN-LAST:event_btnAddNewPatientRecordActionPerformed

    private void btnAddDiagnosisInformationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddDiagnosisInformationActionPerformed
    {//GEN-HEADEREND:event_btnAddDiagnosisInformationActionPerformed
        // TODO add your handling code here:
        AddDiagnosisInformation obj;
        obj = new AddDiagnosisInformation();
        obj.setLocationRelativeTo(this);
        obj.setLocation(450, 180);
        obj.setVisible(true);
        
        btnAddDiagnosisInformation.setEnabled(false);
    }//GEN-LAST:event_btnAddDiagnosisInformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Homepage obj;
                obj = new Homepage();
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton btnAddDiagnosisInformation;
    protected static javax.swing.JButton btnAddNewPatientRecord;
    protected static javax.swing.JButton btnFullHistory;
    protected static javax.swing.JButton btnHospitalInformation;
    private javax.swing.JButton btnLogout;
    protected static javax.swing.JButton btnUpdatePatientRecord;
    private javax.swing.JLabel lblHomepageBackground;
    // End of variables declaration//GEN-END:variables
}
