/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import myPackage.Homepage;

/**
 *
 * @author Prasenjeet Tambe
 */
public class UpdatePatientRecord extends javax.swing.JFrame
{

    /**
     * Creates new form UpdatePatientRecord
     */
    public UpdatePatientRecord()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtPatientID = new javax.swing.JTextField();
        lblParentID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        lblPreviousDisease = new javax.swing.JLabel();
        txtPreviousDisease = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSearchID = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPatientID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 250, 30));

        lblParentID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblParentID.setText("Patient ID");
        getContentPane().add(lblParentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 30));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 250, 30));

        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 30));

        lblContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContact.setText("Contact No.");
        getContentPane().add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, 30));

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAge.setText("Age");
        getContentPane().add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, 30));

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 250, 30));

        cmbGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 250, 30));

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGender.setText("Gender");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, 30));

        lblBloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBloodGroup.setText("Blood Group");
        getContentPane().add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 30));

        txtBloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 250, 30));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 250, 30));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setText("Address");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 30));

        lblPreviousDisease.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPreviousDisease.setText("Any previous major disease suffered?");
        getContentPane().add(lblPreviousDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 368, 30));

        txtPreviousDisease.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPreviousDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 368, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, 35));

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, 35));

        btnSearchID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnSearchID.setText("Search");
        btnSearchID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Search Another ID");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 440, -1, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String patientID = txtPatientID.getText();
        String name = txtName.getText();
        String contactNumber = txtContact.getText();
        String gender = (String) cmbGender.getSelectedItem();
        String age = txtAge.getText();
        String bloodGroup = txtBloodGroup.getText();
        String address = txtAddress.getText();
        String anyDisease = txtPreviousDisease.getText();

        String query = "update patient set name='"+name+"',contactNumber='"+contactNumber+"',age="+age+",gender='"+gender+"',bloodGroup='"+bloodGroup+"',address='"+address+"',anyMajorDisease='"+anyDisease+"' where patientID='"+patientID+"'";

        try
        {

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_database","root","mySQL");
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Patient record saved successfully");

            txtPatientID.setText(null);
            txtName.setText(null);
            txtContact.setText(null);
            txtAge.setText(null);
            txtBloodGroup.setText(null);
            txtAddress.setText(null);
            txtPreviousDisease.setText(null);
            txtPatientID.setEditable(true);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in insertion");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        // TODO add your handling code here:
        var a = JOptionPane.showConfirmDialog(null, "Do you want to Exit?", "Select", JOptionPane.YES_NO_OPTION );

        if(a==0)
        {
            this.dispose();
            Homepage.btnUpdatePatientRecord.setEnabled(true);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchIDActionPerformed
    {//GEN-HEADEREND:event_btnSearchIDActionPerformed
        // TODO add your handling code here:
        String patientID = txtPatientID.getText();
        String query = "select * from patient where patientID = '"+patientID+"'";
         
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_database","root","mySQL");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if(rs.first())
            {
                txtPatientID.setEditable(false);
                
                String name = rs.getString("name");
                String contactNumber = rs.getString("contactNumber");
                String age = rs.getString("age");
                String gender = rs.getString("gender");
                String bloodGroup = rs.getString("bloodGroup");
                String address = rs.getString("address");
                String anyDisease = rs.getString("anyMajorDisease");
                
                txtName.setText(name);
                txtContact.setText(contactNumber);
                txtAge.setText(age);
                cmbGender.setSelectedItem(gender);
                txtBloodGroup.setText(bloodGroup);
                txtAddress.setText(address);
                txtPreviousDisease.setText(anyDisease);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Patient ID not found");
            }
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Connection error");
        }
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        txtName.setText(null);
        txtContact.setText(null);
        txtAge.setText(null);
        txtBloodGroup.setText(null);
        txtAddress.setText(null);
        txtPreviousDisease.setText(null);
        txtPatientID.setEditable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UpdatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UpdatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UpdatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UpdatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UpdatePatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblParentID;
    private javax.swing.JLabel lblPreviousDisease;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPreviousDisease;
    // End of variables declaration//GEN-END:variables
}
